.PHONY: all clean

ASM_PROGRAMS := $(subst .$(ARCHITECTURE).s,,$(wildcard ?-*.$(ARCHITECTURE).s))
REF_PROGRAMS := $(subst .c,,$(wildcard ?-ref.c))

all: $(ASM_PROGRAMS) $(REF_PROGRAMS)

clean:
	$(RM) $(REF_PROGRAMS)

$(REF_PROGRAMS): %: %.c
	$(CC) $(CFLAGS) -fpie -g -march=native -pie -Wall -o $@ $<

%.o: %.$(ARCHITECTURE).s
	$(AS) $(ASFLAGS) -o $@ $<

Makefile.inc: ../mkmk
	../mkmk $(notdir $(CURDIR)) > $@

include Makefile.inc
