#!/usr/bin/env ruby
transformation = {
  '2015-01' => :str,

  '2021-01' => :int,
  '2021-02' => :bin,
  '2021-03' => :bin,
  '2021-04' => :bin,
  '2021-06' => :csvint,
  '2021-07' => :csvint
}

[1, 2].each do |part|
  puts '$(addsuffix .$(ARCHITECTURE).s,$(ASM_PROGRAMS)): %.s: input.inc'
  puts "#{part}-ref.c: input.h"
end

transformation = transformation.fetch ARGV[0]
script = transformation == :bin ? './txt2bin' : "../txt2#{transformation}"
puts "input.inc: input.txt #{script}; #{script} $< > $@"
puts "input.h: input.txt #{script}-ref; #{script}-ref $< > $@"
